word1=input("Enter a word")
word2=input("Enter second word")
word3=input("Enter third word")
word4=input("Enter fourth word")
print("Roses are", word1)
print("Violets are", word2)
print("Sugar is", word3)
print("So are", word4)
